---
- ansible.builtin.include_tasks: redhat-docker.yml
  when: ansible_os_family == 'RedHat'

- ansible.builtin.include_tasks: debian-docker.yml
  when: ansible_os_family == 'Debian'

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/vborodyn/samples/
    state: directory

- name: Copy sources
  ansible.builtin.copy:
    src: /home/vborodyn/samples/
    dest: /root/web/

- name: Pull nginx:alpine image
  community.docker.docker_image:
    name: nginx
    tag: alpine
    source: pull

- name: Run nginx container
  community.docker.docker_container:
    name: nginx_cont
    image: nginx:alpine
    detach: true
    tty: true
    interactive: true
    published_ports:
              - 80:80
    volumes:
              - /root/web/:/usr/share/nginx/html/
